config/routes.rb
Linuxkde::Application.routes.draw do
  resources :visitors
  resources :fonticons

  resources :sections do
    post :sort, on: :collection
    get :list, on: :collection
    get :about, on: :collection

    resources :softwares do
      resources :pages do
        post :sort, on: :collection
        resources :instructions do
          post :sort, on: :collection
          delete :destroyimage
        end
      end
    end
  end

  root to: 'sections#index'
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base

  validates_presence_of :ip

  belongs_to :section
  belongs_to :software
  belongs_to :page
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  def create
    @visitor = Visitor.new(visitor_params)

    if @visitor.save
      redirect_to @visitor, notice: 'Visitor was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /visitors/1
  def update
    if @visitor.update(visitor_params)
      redirect_to @visitor, notice: 'Visitor was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /visitors/1
  def destroy
    @visitor.destroy
    redirect_to visitors_url, notice: 'Visitor was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def visitor_params
      params.require(:visitor).permit(:ip, :section_id, :software_id, :page_id)
    end
end

app/views/visitors/_form.html.haml
= form_for @visitor do |f|
  - if @visitor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@visitor.errors.count, "error")} prohibited this visitor from being saved:"
      %ul
        - @visitor.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :ip
    = f.text_field :ip
  .field
    = f.label :section_id
    = f.number_field :section_id
  .field
    = f.label :software_id
    = f.number_field :software_id
  .field
    = f.label :page_id
    = f.number_field :page_id
  .actions
    = f.submit 'Save'

app/views/visitors/edit.html.haml
%h1 Editing visitor

= render 'form'

= link_to 'Show', @visitor
\|
= link_to 'Back', visitors_path

app/views/visitors/index.html.haml
%h1 Listing visitors

%table
  %tr
    %th Ip
    %th Section
    %th Software
    %th Page
    %th
    %th
    %th

  - @visitors.each do |visitor|
    %tr
      %td= visitor.ip
      %td= visitor.section_id
      %td= visitor.software_id
      %td= visitor.page_id
      %td= link_to 'Show', visitor
      %td= link_to 'Edit', edit_visitor_path(visitor)
      %td= link_to 'Destroy', visitor, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Visitor', new_visitor_path

app/views/visitors/new.html.haml
%h1 New visitor

= render 'form'

= link_to 'Back', visitors_path

app/views/visitors/show.html.haml
%p#notice= notice

%p
  %b Ip:
  = @visitor.ip
%p
  %b Section:
  = @visitor.section_id
%p
  %b Software:
  = @visitor.software_id
%p
  %b Page:
  = @visitor.page_id

= link_to 'Edit', edit_visitor_path(@visitor)
\|
= link_to 'Back', visitors_path