config/routes.rb
Linuxkde::Application.routes.draw do
  resources :visitors
  resources :fonticons

  resources :sections do
    post :sort, on: :collection
    get :list, on: :collection
    get :about, on: :collection

    resources :softwares do
      resources :pages do
        post :sort, on: :collection
        resources :instructions do
          post :sort, on: :collection
          delete :destroyimage
        end
      end
    end
  end

  root to: 'sections#index'
end

app/models/section.rb
class Section < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :icon
  validates_presence_of :position
  validates_presence_of :description
  validates_presence_of :tags

  validates_uniqueness_of :name
  validates_uniqueness_of :icon
  validates_uniqueness_of :tags

  has_many :visitors
  has_many :softwares, dependent: :destroy

  scope :by_position, -> { order(:position) }

  def to_param
    "#{id}-#{name.try(:parameterize)}"
  end

  def name_to_id
    name.parameterize
  end

  def self.set_position(find_id, new_position)
    Section.find(find_id).update_attribute(:position, new_position)
  end

  def self.next_section_position
    return 1 if (Section.count == 0)
    position = Section.all.order('position DESC').limit(1).first.position
    position+1
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :find_section, only: [:show, :edit, :update, :destroy]
  before_action :log_visitors
  before_action :secure_section, except: [:index, :show, :about]

  def index
  end

  def list
  end

  def show
    redirect_to sections_url if !@section.instance_of?(Section)
  end

  def new
    @section = Section.new(position: Section.next_section_position)
  end

  def edit
  end

  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render json: { status: :created, location: @section } }
      else
        format.html { render action: 'new' }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def sort
    unless params[:position].blank?
      params[:position].each_with_index do |id, index|
        Section.set_position(id, index)
      end
    end
    render json: params[:position].to_json
  end

  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url }
      format.json { head :no_content }
    end
  end

  def about
  end

  private
    def section_params
      params.require(:section).permit(:icon,:name,:position,:description,:tags)
    end
end

app/views/sections/_form.html.haml
= form_for @section do |f|
  - if @section.errors.any?
    = error_display(@section)

  .field
    = f.label :icon
    = f.select(:icon, options_for_select(Fonticon.all.map{|ico|[ico.icon, ico.icon]},
      selected: @section.icon))
    %a.btn.icon-preview-button{ href: '#icon-selector-model', title: 'Icon Selector',
                                role: :button, data: { toggle: :modal }}
      %i.fa.fa-th
      %i#preview-icon.fa.fa-exclamation{ title: ' Preview Icon ' }
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :position
    = f.number_field :position
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :tags
    = f.text_field :tags
  .actions
    = f.submit 'Save', class: 'btn btn-primary buttons-submit'

= render partial: 'layouts/icon_selector', locals: { target: '#section_icon' }

app/views/sections/_section_box.html.haml
%br
%blockquote.application-section{ id: section.name_to_id }
  %h2
    %i{ class: "fa #{section.icon}" }
    = link_to section.name, section_url(section)
  %p= section.description
  %small= section.tags
  - if is_admin?
    - add_button('Software', new_section_software_url(section))
    - edit_button('Section', edit_section_url(section))
    - delete_button('Section', section_url(section))

app/views/sections/_section_software_list.html.haml
- softwares.each do |software|
  .software-box
    = render partial: 'softwares/software_box',
      locals: { section: @section, software: software, is_linked: true }

app/views/sections/_welcome.html.haml
.hero-unit
  .header-intro
    This website is for those who wishes to learn Kubuntu.
    The main focus of this website is to show you how to do things in visual
    as much as possible. After all, a picture is worth a thousand words
    and mine starts here.

app/views/sections/about.html.haml
%h2 About

.lead
  This website is was made to inform others that there is an alternative
  operating system out there that is cheaper, better, and easier to use.
  Every instructions in this website has been tested using Kbuntu 12.10.
  Over time some of these instructions may change due to updates of the
  operating system or the software itself. When that happend I will try
  to keep the instructions up to date since I myself use all these softwares.

%p
  This website is created, maintained, and updated by myself so please be
  patient if you don't see as much articles. At this point I will not leave
  any contact information since my current job requires a lot of attention
  from me and I do not have time to read through all emails. In the future
  I will setup an email where you can leave your suggestions or correct any
  mistakes I have made. Thanks for understanding.

app/views/sections/edit.html.haml
%h1 Editing Section
= render 'form'
- back_button('Back to Sections', sections_path)

app/views/sections/index.html.haml
= render partial: 'welcome'

- @sections.each do |section|
  = render partial: 'section_box', locals: { section: section }
  - unless section.softwares.blank?
    .software-list
      - section.softwares.each do |software|
        = render partial: 'softwares/software_box',
          locals: { section: section, software: software, is_linked: true }

%br

- if is_admin?
  .admin-section
    %h3 Administrator
    - add_button('Section', new_section_path)
    - list_button('Sections', list_sections_path)

app/views/sections/list.html.haml
%h1 Listing Sections

#sortable-items{ data: { url: sort_sections_path } }
  - @sections.each do |section|
    .item{ id: section.id }
      .header.sort-mover= section.name
      .info= "Total softwares: #{section.softwares.count}"
      - show_button('Section', section_path(section))
      - edit_button('Section', edit_section_path(section))
      - delete_button('Section', section_path(section))


- if is_admin?
  .admin-section
    %h3 Administrator
    - add_button('Section', new_section_path)

app/views/sections/new.html.haml
%h1 New Section
= render 'form'
- back_button('Back to Sections', sections_path)

app/views/sections/show.html.haml
%p#notice= notice
.breadcrumb
  %li
    = link_to 'Home', sections_path
    %span.divider \
  %li.active= @section.name


= render partial: 'section_box', locals: { section: @section }

- unless @section.softwares.blank?
  = render partial: 'section_software_list',
    locals: { softwares: @section.softwares.by_name }