config/routes.rb
Linuxkde::Application.routes.draw do
  resources :visitors
  resources :fonticons

  resources :sections do
    post :sort, on: :collection
    get :list, on: :collection
    get :about, on: :collection

    resources :softwares do
      resources :pages do
        post :sort, on: :collection
        resources :instructions do
          post :sort, on: :collection
          delete :destroyimage
        end
      end
    end
  end

  root to: 'sections#index'
end

app/views/pages/_form.html.haml
= form_for [@section, @software, @page] do |f|
  - if @page.errors.any?
    = error_display(@page)

  .field
    = f.label :position
    = f.number_field :position
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :enabled
    .make-switch
      = f.check_box :enabled
  .actions
    = f.submit 'Save', class: 'btn btn-primary buttons-submit'

app/views/pages/edit.html.haml
%h1 Editing Page
= render 'form'
- back_button('Back to Page', section_software_page_path(@section, @software, @page))

app/views/pages/index.html.haml
%h1 Listing Pages

#sortable-items{ data: { url: sort_section_software_pages_path(@section,
                                                               @software) } }
  - @software.pages_by_position.each do |page|
    .item{ id: page.id }
      .header.sort-mover
        = page.name
        - if page.enabled
          (enabled)
        - else
          (disabeld)
      .info= "Total instructions: #{page.instructions.count}"
      - show_button('Page',
        section_software_page_path(@section, @software, page))
      - edit_button('Page',
        edit_section_software_page_path(@section, @software, page))
      - delete_button('Page',
        section_software_page_path(@section, @software, page))

%br
- add_button('Page', new_section_software_page_path(@section, @software))
- back_button('Back to Software', section_software_path(@section, @software))

app/views/pages/new.html.haml
%h1 New Page
= render 'form'
- back_button('Back to Software', section_software_path(@section, @software))

app/views/pages/show.html.haml
%p#notice= notice
.breadcrumb
  %li
    = link_to @section.name, sections_path
    %span.divider \
  %li.active= @software.name

= render partial: 'softwares/software_box',
  locals: { section: @section, software: @software }

.row-fluid
  .span8
    .page-contents
      .title= @page.name
      - unless @page.instructions_by_position.blank?
        - @page.instructions_by_position.each do |instruction|
          .instruction= instruction.info.html_safe
          - unless instruction.picture.blank?
            = image_tag instruction.picture.url(:original)

          - if is_admin?
            %br
            - edit_button('Instruction',
                edit_section_software_page_instruction_path(@section,
                @software, @page, instruction))
            - delete_button('Instruction',
                section_software_page_instruction_path(@section,
                @software, @page, instruction))

  .span4
    = render partial: 'softwares/table_of_contents',
      locals: { section: @section, software: @software,
      pages: @software.pages_by_position }

- if is_admin?
  .admin-section
    %h3 Administrator
    - add_button('Instruction',
      new_section_software_page_instruction_path(@section, @software, @page))
    - edit_button('Page', edit_section_software_page_path(@section, @software, @page))
    %br
    - delete_button('Page', section_software_page_path(@section, @software, @page))
    - list_button('Instructions',
      section_software_page_instructions_path(@section, @software, @page))