config/routes.rb
Linuxkde::Application.routes.draw do
  resources :visitors
  resources :fonticons

  resources :sections do
    post :sort, on: :collection
    get :list, on: :collection
    get :about, on: :collection

    resources :softwares do
      resources :pages do
        post :sort, on: :collection
        resources :instructions do
          post :sort, on: :collection
          delete :destroyimage
        end
      end
    end
  end

  root to: 'sections#index'
end

app/models/software.rb
class Software < ActiveRecord::Base

  has_attached_file :icon,
    styles: { large: "200x200>",  medium: "128x128>", small: "64x64>" },
    default_url: "/images/:style/software.png"

  validates_attachment :icon, presence: true, size: { in: 1..500.kilobytes }
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\Z/

  validates_presence_of :section_id
  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :tags

  validates_uniqueness_of :name
  validates_uniqueness_of :tags

  belongs_to :section

  has_many :visitors
  has_many :pages, dependent: :destroy

  scope :by_name, -> { order(:name) }
  scope :by_enabled, -> { where(enabled: true) }

  def to_param
    "#{id}-#{name.try(:parameterize)}"
  end

  def name_to_id
    name.parameterize
  end

  def pages_by_position
    Page.where("software_id = ?", id)
    .order(:position)
  end

  def next_page_position
    return 1 if (pages.count == 0)
    position = pages.order('position DESC').limit(1).first.position
    position+1
  end
end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
  before_action :find_section
  before_action :find_software, only: [:show, :edit, :update, :destroy]
  before_action :log_visitors
  before_action :secure_section, except: [:show]
  before_action :validate_section

  def index
    @softwares = Software.all
  end

  def show
    if is_admin?
      @pages = @software.pages_by_position
    else
      if @software.enabled
        @page = @software.pages_by_position.by_enabled
      else
        redirect_to @section, notice: 'This software is not ready.'
      end
    end
  end

  def new
    @software = Software.new
  end

  def edit
  end

  def create
    @software = Software.new(software_params.merge(section_id: @section.to_param))

    if @software.save
      redirect_to [@section, @software], notice: 'Software was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @software.update(software_params)
      redirect_to [@section, @software], notice: 'Software was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @software.destroy
    redirect_to section_path(@section), notice: 'Software was successfully destroyed.'
  end

  private
    def software_params
      params.require(:software).permit(:icon,
                                       :name,
                                       :description,
                                       :enabled,
                                       :tags)
    end

    def validate_section
      redirect_to sections_url if !@section.instance_of?(Section)
    end
end

app/views/softwares/_form.html.haml
= form_for [@section, @software] do |f|
  - if @software.errors.any?
    = error_display(@software)

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description, class: 'tinymce'
    = tinymce
  .field
    = f.label :tags
    = f.text_field :tags
  .field
    = f.label :icon
    = f.file_field :icon
  .field
    = f.label :enabled
    .make-switch
      = f.check_box :enabled
  %br
  .actions
    = f.submit 'Save', class: 'btn btn-primary buttons-submit'

app/views/softwares/_software_box.html.haml
.row-fluid
  .span8
    .application-cointainer{ id: software.name_to_id }
      .appicon= link_to image_tag(software.icon.url(:medium),
                alt: software.name),
                section_software_path(section, software)
      .header= link_to software.name, section_software_path(section, software)
      .description= software.description.html_safe
      .tags= "- #{software.tags}"

  .span4
    - if is_admin?
      - add_button('Page', new_section_software_page_path(section, software))
      - edit_button('Software', edit_section_software_path(section, software))
      - delete_button('Software', section_software_path(section, software))
      - list_button('Pages', section_software_pages_path(section, software))

app/views/softwares/_table_of_contents.html.haml
- unless pages.blank?
  %ul.nav.nav-tabs.nav-stacked
    - pages.each do |page|
      %li= link_to page.name, section_software_page_path(section, software, page)

- if is_admin?
  - add_button('Page', new_section_software_page_path(section, software))

app/views/softwares/edit.html.haml
%h1 Editing Software
= render 'form'
- back_button('Back to Section', section_path(@section))

app/views/softwares/index.html.haml
%h1 Listing Softwares

%table.table
  %tr
    %th Icon
    %th Name
    %th Enabled
    %th
    %th
    %th

  - @softwares.each do |software|
    %tr
      %td= image_tag software.icon.url(:small)
      %td= software.name
      %td= software.enabled
      %td
        = link_to [@section, software] do
          %i.fa.fa-eye-open
      %td
        = link_to edit_section_software_path(@section, software) do
          %i.fa.fa-edit

- add_button('Software', new_section_software_path(@section))
- back_button('Back to Section', section_path(@section))

app/views/softwares/new.html.haml
%h1 Add New Software
= render 'form'
- back_button('Back to Section', section_path(@section))

app/views/softwares/show.html.haml
%p#notice= notice
.breadcrumb
  %li
    = link_to @section.name, sections_path
    %span.divider \
  %li.active= @software.name

= render partial: 'software_box',
  locals: { section: @section, software: @software }

.row-fluid
  .span8
    - unless @pages.blank?
      .open-book
        = link_to section_software_page_path(@section,
          @software, @pages.first) do
          %i.fa.fa-book
          Start Reading
      .toc
        %h3 Pages
        - @pages.each do |page|
          .page= link_to page.name,
            section_software_page_path(@section, @software, page)

    - if is_admin?
      %br
      - list_button('Pages', section_software_pages_path(@section, @software))

  .span4
    = render partial: 'table_of_contents',
      locals: { section: @section, software: @software,
      pages: @software.pages_by_position  }